import Head from "next/head";
import React, { useState } from "react";
import style from "../styles/Home.module.css";

import CategoriaBotao from "../components/Categorias/";
import CampoDeBusca from "../components/CampoDeBusca/";
import Card from "../components/Cards/";
import { retornarListaProdutos, filtrarItemsMenu, filtrarEntradas, buscarItem } from "../service/index.js";


export default function Home() {

  const [categoria, setCategoria] = useState(filtrarEntradas);
  const [textoDigitado, setTextoDigitado] = useState("");
  const [botaoClicado, setBotaoClicado] = useState("Entradas");

  const handleFiltrarCategoria = (categoria) => {
    setCategoria(filtrarItemsMenu(categoria));
    setBotaoClicado(categoria);
    setTextoDigitado("");
  };

  const handleBuscarItem = (textoDigitado) => {
    setTextoDigitado(textoDigitado);
    setCategoria(buscarItem(textoDigitado));
  };


  return (
    <>
      <Head>
        <title>Restaurante</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Poppins&display=swap" rel="stylesheet" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={`${style.banner} limitar-secao`}>
        <div className={`${style.banner_titulo} limitar-secao`}>
          <h1>Restaurant</h1>
          <p>De pratos clássicos a criações surpreendentes, nosso cardápio é um requinte de sabores refinados</p>
        </div>
      </header>
      <main>
        <section className={`${style.container_elementos_de_busca} limitar-secao`}>
          <CategoriaBotao
            entradas={() => handleFiltrarCategoria("Entradas")}
            massas={() => handleFiltrarCategoria("Massas")}
            carnes={() => handleFiltrarCategoria("Carnes")}
            bebidas={() => handleFiltrarCategoria("Bebidas")}
            saladas={() => handleFiltrarCategoria("Saladas")}
            sobremesas={() => handleFiltrarCategoria("Sobremesas")}
            botaoClidado={botaoClicado}
          />
          <CampoDeBusca
            textoDigitado={textoDigitado}
            filtrarTextoDigitado={(event) => handleBuscarItem(event.target.value)}
          />
        </section>
        <section className={`${style.container_cardapio} limitar-secao`}>
          <h3>Cardapio</h3>
          <div className={style.container_card}> {
            categoria.map((item) => (
              <Card
                key={item.id}
                imagem={item.imagem}
                nome={item.nome}
                categoria={item.categoria}
                descricao={item.descricao}
                preco={item.preco}
              />
            ))}
          </div>
        </section>
      </main>
    </>
  );
}
