import Head from "next/head";
import React, { useState } from "react";
import style from "../styles/Home.module.css";

import { retornarListaProdutos, filtrarItemsMenu, buscarItem } from "../service/index.js";

import CategoriaBotao from "../components/Categorias/";
import CampoDeBusca from "../components/CampoDeBusca/";
import Card from "../components/Cards/";


export default function Home() {

  const [categoria, setCategoria] = useState(retornarListaProdutos());

  const handleFiltrarCategoria = (categoria) => {
    setCategoria(filtrarItemsMenu(categoria));
  };


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Poppins&display=swap" rel="stylesheet" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className={`limitar-secao`}>
          <h1>Restaurant</h1>
          <p></p>
        </div>
      </header>
      <main>
        <section className={`${style.container_elementos_de_busca} limitar-secao`}>
          <CategoriaBotao
          entradas={() => handleFiltrarCategoria()}
          massas={() => handleFiltrarCategoria()}
          carnes={() => handleFiltrarCategoria()}
          bebidas={() => handleFiltrarCategoria()}
          saladas={() => handleFiltrarCategoria()}
          sobremesas={() => handleFiltrarCategoria()}
          />
          <div>
            <CampoDeBusca />
          </div>
        </section>
        <section className={`${style.container_cardapio} limitar-secao`}>
          <h3>Cardapio</h3>
          <div className={style.container_card}> {
            categoria.map((item) => (
              <Card
                imagem={item.imagem}
                nome={item.nome}
                categoria={item.categoria}
                descricao={item.descricao}
                preco={item.preco}
              />
            ))}
          </div>
        </section>
      </main>
    </>
  );
}
